# Move and rename Certification files
$basePath = "d:\QA_Automation-master\QA_Automation-master\tests\admin\trainingPlan"
Set-Location $basePath

# Certification files mapping
$certFiles = @(
    @{Old="TP001_Verify_learner_is_autoenrolled_to_mandatory_Certification.spec.ts"; New="CER001_Verify_learner_is_autoenrolled_to_mandatory_Certification.spec.ts"},
    @{Old="TP003_Verify_certification_status_is_changed_to_overdue_when_the_date_is_set.spec.ts"; New="CER002_Verify_certification_status_is_changed_to_overdue_when_the_date_is_set.spec.ts"},
    @{Old="TP005_Verify_that_the_learner_is_able_to_launch_and_complete_a_certification_that_was_revoked_by_the_admin.spec.ts"; New="CER003_Verify_that_the_learner_is_able_to_launch_and_complete_a_certification_that_was_revoked_by_the_admin.spec.ts"},
    @{Old="TP006_Verify_certification_status_is_changed_to_incomplete_when_the_date_is_set.spec.ts"; New="CER004_Verify_certification_status_is_changed_to_incomplete_when_the_date_is_set.spec.ts"},
    @{Old="TP007_Verify_lp_status_is_changed_to_incomplete_when_the_date_is_set.spec.ts"; New="CER005_Verify_lp_status_is_changed_to_incomplete_when_the_date_is_set.spec.ts"},
    @{Old="TP008_confirm_that_the_rollback_occurs_successfully_when_a_learner_completes_the_course_and_then_registers_for_the_certification.spec.ts"; New="CER006_confirm_that_the_rollback_occurs_successfully_when_a_learner_completes_the_course_and_then_registers_for_the_certification.spec.ts"},
    @{Old="TP009_Verify_that_a_course_enrolled_via_TP_is_not_available_as_a_standalone_in_the_course_catalog.spec.ts"; New="CER007_Verify_that_a_course_enrolled_via_TP_is_not_available_as_a_standalone_in_the_course_catalog.spec.ts"},
    @{Old="TP010_Confirm_whether_a_rollback_does_not_occur_when_a_learner_enrolls_in_an_already_completed_course_as_part_of_the_recertification_path.spec.ts"; New="CER008_Confirm_whether_a_rollback_does_not_occur_when_a_learner_enrolls_in_an_already_completed_course_as_part_of_the_recertification_path.spec.ts"},
    @{Old="TP011_Verify_rollback_does_not_occur_when_the_same_course_is_attached_in_both_Certification_and_Recertification_paths.spec.ts"; New="CER009_Verify_rollback_does_not_occur_when_the_same_course_is_attached_in_both_Certification_and_Recertification_paths.spec.ts"},
    @{Old="TP015_Verify_that_certification_enrollment_and_completion_occurred_at_the_module_level.spec.ts"; New="CER010_Verify_that_certification_enrollment_and_completion_occurred_at_the_module_level.spec.ts"},
    @{Old="TP016_Confirm_that_a_learner_can_successfully_register_for_and_complete_a_certification_through_a_single-instance_course.spec.ts"; New="CER011_Confirm_that_a_learner_can_successfully_register_for_and_complete_a_certification_through_a_single-instance_course.spec.ts"},
    @{Old="TP017_Confirm_that_a_learner_can_successfully_register_the_certification.spec.ts"; New="CER012_Confirm_that_a_learner_can_successfully_register_the_certification.spec.ts"},
    @{Old="TP018_Verify_that_a_learner_can_successfully_enroll_in_a_certification_that_includes_a_multi-instance_course.spec.ts"; New="CER013_Verify_that_a_learner_can_successfully_enroll_in_a_certification_that_includes_a_multi-instance_course.spec.ts"},
    @{Old="TP019_Verify_certification_expiration_flow.spec.ts"; New="CER014_Verify_certification_expiration_flow.spec.ts"},
    @{Old="TP020_Verify_learner_able_to_re-certify_the_expired_certification.spec.ts"; New="CER015_Verify_learner_able_to_re-certify_the_expired_certification.spec.ts"},
    @{Old="TP021_Verify_certification_priced_flow.spec.ts"; New="CER016_Verify_certification_priced_flow.spec.ts"},
    @{Old="TP022_Verify_the_certification_compliance_flow.spec.ts"; New="CER017_Verify_the_certification_compliance_flow.spec.ts"},
    @{Old="TP024_Verify_the_Enforce_Sequence_flow_Cert.spec.ts"; New="CER018_Verify_the_Enforce_Sequence_flow_Cert.spec.ts"},
    @{Old="TP025_Ensure_that_a_Learning_Path_created_in_one_portal_is_not_displayed_or_accessible_in_any_other_portal.spec.ts"; New="CER019_Ensure_that_a_Learning_Path_created_in_one_portal_is_not_displayed_or_accessible_in_any_other_portal.spec.ts"},
    @{Old="TP030_Verify_the_Select_Class_functionality_on_the_Enrollment_page_for-the_Training_Plan.spec.ts"; New="CER020_Verify_the_Select_Class_functionality_on_the_Enrollment_page_for-the_Training_Plan.spec.ts"},
    @{Old="TP049_Cert_prerequisite_warning_enrollment.spec.ts"; New="CER021_Cert_prerequisite_warning_enrollment.spec.ts"},
    @{Old="TP049_Verify_enrolled_certification_courses_in_my_learning_to_complete.spec.ts"; New="CER022_Verify_enrolled_certification_courses_in_my_learning_to_complete.spec.ts"},
    @{Old="TP050_Cert_maincourse_prerequisite_warning_admin.spec.ts"; New="CER023_Cert_maincourse_prerequisite_warning_admin.spec.ts"},
    @{Old="TP050_Verify_certification_with_complete_by_rule_and_SCORM_content.spec.ts"; New="CER024_Verify_certification_with_complete_by_rule_and_SCORM_content.spec.ts"},
    @{Old="TP051_Cert_maincourse_prerequisite_warning_learner.spec.ts"; New="CER025_Cert_maincourse_prerequisite_warning_learner.spec.ts"},
    @{Old="TP051_Verify_certification_with_complete_by_days_from_enrollment_and_AICC_content.spec.ts"; New="CER026_Verify_certification_with_complete_by_days_from_enrollment_and_AICC_content.spec.ts"},
    @{Old="TP052_Cert_prerequisite_at_cert_and_course_level.spec.ts"; New="CER027_Cert_prerequisite_at_cert_and_course_level.spec.ts"},
    @{Old="TP052_Verify_certification_with_complete_by_days_from_hire_and_Video_content.spec.ts"; New="CER028_Verify_certification_with_complete_by_days_from_hire_and_Video_content.spec.ts"},
    @{Old="TP053_Cert_prerequisite_behavior_learner_side.spec.ts"; New="CER029_Cert_prerequisite_behavior_learner_side.spec.ts"},
    @{Old="TP053_Verify_certification_not_auto_enrolled_with_optional_access.spec.ts"; New="CER030_Verify_certification_not_auto_enrolled_with_optional_access.spec.ts"},
    @{Old="TP054_Admin_cert_prerequisite_already_completed.spec.ts"; New="CER031_Admin_cert_prerequisite_already_completed.spec.ts"},
    @{Old="TP054_Verify_mandatory_certification_cannot_be_canceled.spec.ts"; New="CER032_Verify_mandatory_certification_cannot_be_canceled.spec.ts"},
    @{Old="TP055_Create_3_multi_instance_courses_and_attach_to_certification.spec.ts"; New="CER033_Create_3_multi_instance_courses_and_attach_to_certification.spec.ts"},
    @{Old="TP055_Learner_cert_prerequisite_already_completed.spec.ts"; New="CER034_Learner_cert_prerequisite_already_completed.spec.ts"},
    @{Old="TP056_Pre_post_assessment_score_cert.spec.ts"; New="CER035_Pre_post_assessment_score_cert.spec.ts"},
    @{Old="TP056_Verify_compliance_certification_expiration_with_anniversary_completion_date_fixed.spec.ts"; New="CER036_Verify_compliance_certification_expiration_with_anniversary_completion_date_fixed.spec.ts"},
    @{Old="TP057_Cert_assessment_questions_display.spec.ts"; New="CER037_Cert_assessment_questions_display.spec.ts"},
    @{Old="TP057_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_month.spec.ts"; New="CER038_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_month.spec.ts"},
    @{Old="TP058_Cert_section_assessment_display.spec.ts"; New="CER039_Cert_section_assessment_display.spec.ts"},
    @{Old="TP058_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_quarter.spec.ts"; New="CER040_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_quarter.spec.ts"},
    @{Old="TP059_Cert_retake_assessment_without_section.spec.ts"; New="CER041_Cert_retake_assessment_without_section.spec.ts"},
    @{Old="TP059_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_year.spec.ts"; New="CER042_Verify_compliance_certification_expiration_with_anniversary_birth_date_period_year.spec.ts"},
    @{Old="TP060_Cert_retake_assessment_with_section.spec.ts"; New="CER043_Cert_retake_assessment_with_section.spec.ts"},
    @{Old="TP060_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_month.spec.ts"; New="CER044_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_month.spec.ts"},
    @{Old="TP061_CEU_inherited_to_certification.spec.ts"; New="CER045_CEU_inherited_to_certification.spec.ts"},
    @{Old="TP061_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_quarter.spec.ts"; New="CER046_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_quarter.spec.ts"},
    @{Old="TP062_Cert_survey_questions_display.spec.ts"; New="CER047_Cert_survey_questions_display.spec.ts"},
    @{Old="TP062_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_year.spec.ts"; New="CER048_Verify_compliance_certification_expiration_with_anniversary_hire_date_period_year.spec.ts"},
    @{Old="TP063_Cert_survey_consider_for_completion.spec.ts"; New="CER049_Cert_survey_consider_for_completion.spec.ts"},
    @{Old="TP063_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_month.spec.ts"; New="CER050_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_month.spec.ts"},
    @{Old="TP064_Cert_section_survey_display.spec.ts"; New="CER051_Cert_section_survey_display.spec.ts"},
    @{Old="TP064_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_quarter.spec.ts"; New="CER052_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_quarter.spec.ts"},
    @{Old="TP065_Cert_equivalence_status.spec.ts"; New="CER053_Cert_equivalence_status.spec.ts"},
    @{Old="TP065_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_year.spec.ts"; New="CER054_Verify_compliance_certification_expiration_with_anniversary_enrollment_date_period_year.spec.ts"},
    @{Old="TP066_Cert_completion_rollback.spec.ts"; New="CER055_Cert_completion_rollback.spec.ts"},
    @{Old="TP066_Verify_compliance_certification_recertification_with_completion_date_and_complete_by_date.spec.ts"; New="CER056_Verify_compliance_certification_recertification_with_completion_date_and_complete_by_date.spec.ts"},
    @{Old="TP067_Recertification_assessments_survey.spec.ts"; New="CER057_Recertification_assessments_survey.spec.ts"},
    @{Old="TP067_Verify_compliance_certification_recertification_with_anniversary_birth_date_month_and_days_from_enrollment.spec.ts"; New="CER058_Verify_compliance_certification_recertification_with_anniversary_birth_date_month_and_days_from_enrollment.spec.ts"},
    @{Old="TP068_Cert_assessment_attempt_limit_incomplete.spec.ts"; New="CER059_Cert_assessment_attempt_limit_incomplete.spec.ts"},
    @{Old="TP068_Verify_compliance_certification_recertification_with_anniversary_birth_date_quarter_and_days_from_hire.spec.ts"; New="CER060_Verify_compliance_certification_recertification_with_anniversary_birth_date_quarter_and_days_from_hire.spec.ts"},
    @{Old="TP070_Cert_post_assessment_passing_score.spec.ts"; New="CER061_Cert_post_assessment_passing_score.spec.ts"},
    @{Old="TP069_Verify_compliance_certification_recertification_with_anniversary_birth_date_year_and_complete_by_date.spec.ts"; New="CER062_Verify_compliance_certification_recertification_with_anniversary_birth_date_year_and_complete_by_date.spec.ts"},
    @{Old="TP070_Verify_compliance_certification_recertification_with_anniversary_hire_date_month_and_days_from_enrollment.spec.ts"; New="CER063_Verify_compliance_certification_recertification_with_anniversary_hire_date_month_and_days_from_enrollment.spec.ts"},
    @{Old="TP071_Verify_compliance_certification_recertification_with_anniversary_hire_date_quarter_and_days_from_hire.spec.ts"; New="CER064_Verify_compliance_certification_recertification_with_anniversary_hire_date_quarter_and_days_from_hire.spec.ts"},
    @{Old="TP072_Revalidate_certification_after_completion.spec.ts"; New="CER065_Revalidate_certification_after_completion.spec.ts"},
    @{Old="TP072_Verify_compliance_certification_recertification_with_anniversary_hire_date_year_and_complete_by_date.spec.ts"; New="CER066_Verify_compliance_certification_recertification_with_anniversary_hire_date_year_and_complete_by_date.spec.ts"},
    @{Old="TP073_Revalidated_cert_status_change.spec.ts"; New="CER067_Revalidated_cert_status_change.spec.ts"},
    @{Old="TP073_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_month_and_days_from_enrollment.spec.ts"; New="CER068_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_month_and_days_from_enrollment.spec.ts"},
    @{Old="TP074_Revalidate_expired_recertification.spec.ts"; New="CER069_Revalidate_expired_recertification.spec.ts"},
    @{Old="TP074_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_quarter_and_days_from_hire.spec.ts"; New="CER070_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_quarter_and_days_from_hire.spec.ts"},
    @{Old="TP075_Revalidated_cert_INA_visibility.spec.ts"; New="CER071_Revalidated_cert_INA_visibility.spec.ts"},
    @{Old="TP075_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_year_and_complete_by_date.spec.ts"; New="CER072_Verify_compliance_certification_recertification_with_anniversary_enrollment_date_year_and_complete_by_date.spec.ts"},
    @{Old="TP076_Revalidate_cert_within_window_period.spec.ts"; New="CER073_Revalidate_cert_within_window_period.spec.ts"},
    @{Old="TP076_Verify_compliance_certification_recertification_with_completion_date_and_days_from_enrollment.spec.ts"; New="CER074_Verify_compliance_certification_recertification_with_completion_date_and_days_from_enrollment.spec.ts"},
    @{Old="TP077_Verify_certification_with_optional_course_and_enforce_sequence.spec.ts"; New="CER075_Verify_certification_with_optional_course_and_enforce_sequence.spec.ts"},
    @{Old="TP078_Verify_cert_status_is_changed_to_overdue_with_days_from_enrollment.spec.ts"; New="CER076_Verify_cert_status_is_changed_to_overdue_with_days_from_enrollment.spec.ts"},
    @{Old="TP079_Cert_EL_course_status.spec.ts"; New="CER077_Cert_EL_course_status.spec.ts"},
    @{Old="TP079_Verify_cert_status_is_changed_to_overdue_with_days_from_hire.spec.ts"; New="CER078_Verify_cert_status_is_changed_to_overdue_with_days_from_hire.spec.ts"},
    @{Old="TP080_Cert_multi_instance_course_status.spec.ts"; New="CER079_Cert_multi_instance_course_status.spec.ts"},
    @{Old="TP080_Verify_cert_status_is_changed_to_incomplete_with_days_from_enrollment.spec.ts"; New="CER080_Verify_cert_status_is_changed_to_incomplete_with_days_from_enrollment.spec.ts"},
    @{Old="TP081_ReCertification_EL_course_status.spec.ts"; New="CER081_ReCertification_EL_course_status.spec.ts"},
    @{Old="TP081_Verify_cert_status_is_changed_to_incomplete_with_days_from_hire.spec.ts"; New="CER082_Verify_cert_status_is_changed_to_incomplete_with_days_from_hire.spec.ts"},
    @{Old="TP082_Verify_certification_with_reorder_delete_optional_and_enforce_sequence.spec.ts"; New="CER083_Verify_certification_with_reorder_delete_optional_and_enforce_sequence.spec.ts"},
    @{Old="TP083_Verify_mandatory_certification_multiple_groups_and_users.spec.ts"; New="CER084_Verify_mandatory_certification_multiple_groups_and_users.spec.ts"},
    @{Old="TP084_Verify_comprehensive_certification_with_all_features.spec.ts"; New="CER085_Verify_comprehensive_certification_with_all_features.spec.ts"},
    @{Old="TP085_Verify_certification_expiration_with_specific_date.spec.ts"; New="CER086_Verify_certification_expiration_with_specific_date.spec.ts"},
    @{Old="TP086_Verify_admin_able_to_create_certification_with_modules.spec.ts"; New="CER087_Verify_admin_able_to_create_certification_with_modules.spec.ts"},
    @{Old="TP087_Verify_admin_able_to_create_certification_with_multiple_modules_separately.spec.ts"; New="CER088_Verify_admin_able_to_create_certification_with_multiple_modules_separately.spec.ts"},
    @{Old="TP088_Verify_admin_able_to_create_certification_with_multi_instance_courses_at_module_level.spec.ts"; New="CER089_Verify_admin_able_to_create_certification_with_multi_instance_courses_at_module_level.spec.ts"},
    @{Old="TP089_Verify_compliance_certification_recertification_expiry_with_anniversary_completion_date_fixed.spec.ts"; New="CER090_Verify_compliance_certification_recertification_expiry_with_anniversary_completion_date_fixed.spec.ts"},
    @{Old="TP090_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_month.spec.ts"; New="CER091_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_month.spec.ts"},
    @{Old="TP091_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_quarter.spec.ts"; New="CER092_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_quarter.spec.ts"},
    @{Old="TP092_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_year.spec.ts"; New="CER093_Verify_compliance_certification_recertification_expiry_with_anniversary_birth_date_period_year.spec.ts"},
    @{Old="TP093_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_month.spec.ts"; New="CER094_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_month.spec.ts"},
    @{Old="TP094_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_quarter.spec.ts"; New="CER095_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_quarter.spec.ts"},
    @{Old="TP095_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_year.spec.ts"; New="CER096_Verify_compliance_certification_recertification_expiry_with_anniversary_hire_date_period_year.spec.ts"},
    @{Old="TP096_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_month.spec.ts"; New="CER097_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_month.spec.ts"},
    @{Old="TP097_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_quarter.spec.ts"; New="CER098_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_quarter.spec.ts"},
    @{Old="TP098_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_year.spec.ts"; New="CER099_Verify_compliance_certification_recertification_expiry_with_anniversary_enrollment_date_period_year.spec.ts"},
    @{Old="TP099_Verify_compliance_certification_recertification_expiry_with_completion_date.spec.ts"; New="CER100_Verify_compliance_certification_recertification_expiry_with_completion_date.spec.ts"},
    @{Old="TP100_Verify_certification_expiration_with_anniversary_date.spec.ts"; New="CER101_Verify_certification_expiration_with_anniversary_date.spec.ts"},
    @{Old="TP101_Verify_certification_expiration_with_anniversary_birth_date_period_month.spec.ts"; New="CER102_Verify_certification_expiration_with_anniversary_birth_date_period_month.spec.ts"},
    @{Old="TP102_Verify_certification_expiration_with_anniversary_birth_date_period_quarter.spec.ts"; New="CER103_Verify_certification_expiration_with_anniversary_birth_date_period_quarter.spec.ts"},
    @{Old="TP103_Verify_certification_expiration_with_anniversary_birth_date_period_year.spec.ts"; New="CER104_Verify_certification_expiration_with_anniversary_birth_date_period_year.spec.ts"},
    @{Old="TP104_Verify_certification_expiration_with_anniversary_hire_date_period_month.spec.ts"; New="CER105_Verify_certification_expiration_with_anniversary_hire_date_period_month.spec.ts"},
    @{Old="TP105_Verify_certification_expiration_with_anniversary_hire_date_period_quarter.spec.ts"; New="CER106_Verify_certification_expiration_with_anniversary_hire_date_period_quarter.spec.ts"},
    @{Old="TP106_Verify_certification_expiration_with_anniversary_hire_date_period_year.spec.ts"; New="CER107_Verify_certification_expiration_with_anniversary_hire_date_period_year.spec.ts"},
    @{Old="TP107_Verify_certification_expiration_with_anniversary_enrollment_date_period_month.spec.ts"; New="CER108_Verify_certification_expiration_with_anniversary_enrollment_date_period_month.spec.ts"},
    @{Old="TP108_Verify_certification_expiration_with_anniversary_enrollment_date_period_quarter.spec.ts"; New="CER109_Verify_certification_expiration_with_anniversary_enrollment_date_period_quarter.spec.ts"},
    @{Old="TP109_Verify_certification_expiration_with_anniversary_enrollment_date_period_year.spec.ts"; New="CER110_Verify_certification_expiration_with_anniversary_enrollment_date_period_year.spec.ts"},
    @{Old="TP110_Verify_certification_auto_enrollment_after_expiry_with_mandatory_access.spec.ts"; New="CER111_Verify_certification_auto_enrollment_after_expiry_with_mandatory_access.spec.ts"},
    @{Old="TP111_Verify_mandatory_certification_cannot_be_canceled.spec.ts"; New="CER112_Verify_mandatory_certification_cannot_be_canceled.spec.ts"},
    @{Old="TPT0113_Clone_Certification_and_Verify.spec.ts"; New="CER113_Clone_Certification_and_Verify.spec.ts"},
    @{Old="Data_TP.spec.ts"; New="CER114_Data_TP.spec.ts"}
)

foreach ($file in $certFiles) {
    $oldPath = Join-Path $basePath $file.Old
    $newPath = Join-Path $basePath "Certification" $file.New
    if (Test-Path $oldPath) {
        Move-Item -Path $oldPath -Destination $newPath -Force
        Write-Host "Moved: $($file.Old) -> $($file.New)"
    } else {
        Write-Host "File not found: $($file.Old)"
    }
}

Write-Host "`nCertification files migration completed!"
