import { test } from "../../../customFixtures/expertusFixture";
import { FakerData } from '../../../utils/fakerUtils';
import { AdminRoleManager } from "../../../utils/adminRoleManager";
import { UserPage } from "../../../pages/UserPage";
import { } from "../../../pages/AdminHomePage";
import { AdminGroupPage } from "../../../pages/AdminGroupPage";


let username = FakerData.getUserId();
let role: any;
let systemDefaultRole: any;
test.describe(`Verify Admin Group Code Auto-Generation with Code Convention`, async () => {
    test.describe.configure({ mode: 'serial' })
    test(`Verify whether the Code is autogenerated `, async ({ adminHome, createUser, createCourse, adminGroup, siteAdmin }) => {
        test.info().annotations.push(
            { type: `Author`, description: `Divya` },
            { type: `TestCase`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convention` },
            { type: `Test Description`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convention` }
        );
        await adminHome.loadAndLogin("CUSTOMERADMIN");
        await adminHome.menuButton();
        await adminHome.siteAdmin();
        await adminHome.siteAdmin_Adminconfig();
        await siteAdmin.autoCodeConventionTurnON();
        await adminHome.menuButton();
        await adminHome.people();
        await adminHome.adminGroup();
        await adminGroup.clickCreateGroup();
        await adminGroup.enterGroupTitle(FakerData.getSession());
        await adminGroup.clickSaveBtn();
        await adminGroup.clickProceed();
        await createCourse.verifySuccessMessage();
        await adminGroup.clickEditGroup();
        await adminGroup.getAdminGroupCode();

    })


});