import { test } from "../../../customFixtures/expertusFixture";
import { FakerData } from '../../../utils/fakerUtils';
import { AdminRoleManager } from "../../../utils/adminRoleManager";
import { UserPage } from "../../../pages/UserPage";
import { } from "../../../pages/AdminHomePage";
import { AdminGroupPage } from "../../../pages/AdminGroupPage";


const title=FakerData.getRandomTitle();
const title1=FakerData.getRandomTitle();
test.describe(`Verify whether the Code is autogenerated correctly when we enable the Code Convention`, async () => {
    test.describe.configure({ mode: 'serial' })
    test(`Verify whether the autogenerated correctly when we enable the Code Convention`, async ({ adminHome, contentHome, bannerHome, createCourse, adminGroup, siteAdmin }) => {
        test.info().annotations.push(
            { type: `Author`, description: `Divya` },
            { type: `TestCase`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convent` },
            { type: `Test Description`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convent` }
        );
        await adminHome.loadAndLogin("CUSTOMERADMIN");
        await adminHome.menuButton();
        await adminHome.siteAdmin();
        await adminHome.siteAdmin_Adminconfig();
        await siteAdmin.autoCodeConventionTurnON();
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickContentmenu();
        await contentHome.clickCreateContent();
        await contentHome.enterTitle(title);
        await contentHome.enterDescription("Sample video content for " + title);
        await contentHome.uploadContent("Original_recording5.mp4");
        await bannerHome.clickPublish();
        await createCourse.clickProceed();
        await createCourse.verifySuccessMessage();
        await contentHome.clickEditContent();
        await contentHome.getCntCode();
    })

     test(`Verify whether the Code is not autogenerated when we disable the Code Convention`, async ({ adminHome, contentHome, bannerHome, createCourse, adminGroup, siteAdmin }) => {
        test.info().annotations.push(
            { type: `Author`, description: `Divya` },
            { type: `TestCase`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convent` },
            { type: `Test Description`, description: `Verify whether the Code is autogenerated correctly when we enable the Code Convent` }
        );
        await adminHome.loadAndLogin("CUSTOMERADMIN");
        await adminHome.menuButton();
        await adminHome.siteAdmin();
        await adminHome.siteAdmin_Adminconfig();
        await siteAdmin.autoCodeConventionTurnOFF();
        await siteAdmin.clickOkBtn();
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickContentmenu();
        await contentHome.clickCreateContent();
        await contentHome.enterTitle(title);
        await contentHome.enterDescription("Sample video content for " + title);
        await contentHome.uploadContent("Original_recording5.mp4");
        await bannerHome.clickPublish();
        await createCourse.clickProceed();
        await createCourse.verifySuccessMessage();
        await contentHome.clickEditContent();
        await contentHome.getCntCode();
    })


});