import { test } from "../../../customFixtures/expertusFixture"
import { FakerData } from '../../../utils/fakerUtils';

// Course creation functions 
const courseName = FakerData.getCourseName();
const description = FakerData.getDescription();
const shareEmail = 'nithyas@peopleone.co';

test.describe(`Direct Content Launch Share URL functionality`, async () => {
    test.describe.configure({ mode: "serial" });
    
    test(`DCL010 - Generate and Share Direct Content Launch URL`, async ({ adminHome, createCourse, directContent }) => {
        test.info().annotations.push(
            { type: `Author`, description: `AutoGenerated` },
            { type: `TestCase`, description: `DCL010 - Generate and Share Direct Content Launch URL` },
            { type: `Test Description`, description: `Create a course, generate DCL URL, and share via email` }
        );

        // Login as admin
        await adminHome.loadAndLogin("CUSTOMERADMIN1");
        
        // Navigate to Course creation
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickCourseLink();
        
        // Create a new course
        await createCourse.clickCreateCourse();
        await createCourse.verifyCreateUserLabel("CREATE COURSE");
        await createCourse.enter("course-title", courseName);
        await createCourse.selectLanguage("English");
        await createCourse.typeDescription("This is a new course for share URL testing: " + description);
        await createCourse.contentLibrary("clip-oceans");
        await createCourse.clickCatalog();
        await createCourse.clickSave();
        await createCourse.clickProceed();
        await createCourse.verifySuccessMessage();
        
        // Navigate to Direct Content Launch
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickDirectContentLaunchLink();
        
        // Generate URL for the course
        await directContent.clickdomaindropdown("newprod");
        await directContent.searchfield(courseName);
        
        const isUrlGenerated = await directContent.generateURL();
        
        if (isUrlGenerated) {
            // Copy URL first to verify it's generated
            const copiedURL = await directContent.copyURL();
            await directContent.verifySuccessMessage();
            
            console.log(`Generated URL: ${copiedURL}`);
            
            // Share the URL via email
            await directContent.shareURLWithEmail(shareEmail);
            
            // Clear fields after sharing
            await directContent.clearFields();
            
            console.log(`URL shared successfully to: ${shareEmail}`);
        } else {
            console.log("Cannot share URL as generation failed for this course");
        }
    });

    test(`DCL011 - Verify Share URL Modal functionality`, async ({ adminHome, directContent }) => {
        test.info().annotations.push(
            { type: `Author`, description: `AutoGenerated` },
            { type: `TestCase`, description: `DCL011 - Verify Share URL Modal functionality` },
            { type: `Test Description`, description: `Test Share URL modal open, close, and cancel functionality` }
        );

        // Login as admin
        await adminHome.loadAndLogin("CUSTOMERADMIN1");
        
        // Navigate to Direct Content Launch
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickDirectContentLaunchLink();
        
        // Select domain and search for a course
        await directContent.clickdomaindropdown("newprod");
        await directContent.searchfield(courseName);
        
        const isUrlGenerated = await directContent.generateURL();
        
        if (isUrlGenerated) {
            // Test modal open and close
            await directContent.clickShareURL();
            await directContent.verifyShareModal();
            //await directContent.closeShareModal();
            
            // Test modal open and cancel
            await directContent.clickShareURL();
            await directContent.verifyShareModal();
            await directContent.cancelShare();
            
            console.log("Share URL modal functionality tested successfully");
        } else {
            console.log("Cannot test share modal as URL generation failed");
        }
    });

    test(`DCL012 - Share URL with multiple email addresses`, async ({ adminHome, directContent }) => {
        test.info().annotations.push(
            { type: `Author`, description: `AutoGenerated` },
            { type: `TestCase`, description: `DCL012 - Share URL with multiple email addresses` },
            { type: `Test Description`, description: `Share generated DCL URL with multiple recipients` }
        );

        const email1 ="nithyas@peopleone.co";
        const email2 = "tamilvanans@peopleone.co";
        const email3 = "balasundarm@peopleone.co";

        // Login as admin
        await adminHome.loadAndLogin("CUSTOMERADMIN1");
        
        // Navigate to Direct Content Launch
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickDirectContentLaunchLink();
        
        // Select domain and search for a course
        await directContent.clickdomaindropdown("newprod");
        await directContent.searchfield(courseName);
        
        const isUrlGenerated = await directContent.generateURL();
        
        if (isUrlGenerated) {
            // Share with multiple emails
            const emails = [email1, email2, email3];

            await directContent.shareURLWithMultipleEmails(emails);
            
            // for (const email of emails) {
             //  await directContent.shareURLWithEmail(email);
            //     console.log(`URL shared with: ${email}`);
            //     await directContent.wait("minWait"); // Small wait between shares
            // }
            
            console.log("URL shared successfully with multiple recipients");
            
            // Clear fields after all sharing
            await directContent.clearFields();
        } else {
            console.log("Cannot share URL as generation failed");
        }
    });
});