import { credentials } from "../../../constants/credentialData";
import { test } from "../../../customFixtures/expertusFixture"
import { LearnerHomePage } from "../../../pages/LearnerHomePage";
import { FakerData } from '../../../utils/fakerUtils';


//course creation fuctions 
const courseName = FakerData.getCourseName();
const description = FakerData.getDescription()
let URL:any
let createdCode: any

    test.describe.configure({ mode: "serial" });
test.describe(`Direct Content Launch Learner Signup Popup Verification`, async () => {
    test.describe.configure({ mode: "serial" });
    
    let directContentURL: string;

    test(`DCL013 - Create course and generate Direct Content URL for signup testing`, async ({ adminHome, createCourse, directContent }) => {
        test.info().annotations.push(
            { type: `Author`, description: `AutoGenerated` },
            { type: `TestCase`, description: `DCL013 - Create course and generate DCL URL for signup testing` },
            { type: `Test Description`, description: `Create a course and generate Direct Content Launch URL for learner signup testing` }
        );

        // Login as admin
        await adminHome.loadAndLogin("CUSTOMERADMIN1");
        
        // Navigate to Course creation
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickCourseLink();
        
        // Create a new course
        await createCourse.clickCreateCourse();
        await createCourse.verifyCreateUserLabel("CREATE COURSE");
        await createCourse.enter("course-title", courseName);
        await createCourse.selectLanguage("English");
        await createCourse.typeDescription("Course for learner signup testing: " + description);
        await createCourse.contentLibrary("clip-oceans");
        await createCourse.clickCatalog();
        await createCourse.clickSave();
        await createCourse.clickProceed();
        await createCourse.verifySuccessMessage();
        
        // Navigate to Direct Content Launch
        await adminHome.menuButton();
        await adminHome.clickLearningMenu();
        await adminHome.clickDirectContentLaunchLink();
        
        // Generate URL for the course
        await directContent.clickdomaindropdown("newprod");
        await directContent.searchfield(courseName);
        
        const isUrlGenerated = await directContent.generateURL();
        
        if (isUrlGenerated) {
            // Copy URL for learner side testing
            directContentURL = await directContent.copyURL();
            await directContent.verifySuccessMessage();
            
            console.log(`Generated Direct Content URL: ${directContentURL}`);
            
            // Store the URL for use in subsequent tests
            process.env.DIRECT_CONTENT_URL = directContentURL;
        } else {
            throw new Error("Failed to generate Direct Content URL");
        }
    });

    test(`Launching the content through direct content launch in learner side`, async ({ directContent,learnerHome, catalog , page, context}) => {
            test.info().annotations.push(
                { type: `Author`, description: `Nithya` },
                { type: `TestCase`, description: `DCL014 - Verify signup popup appears for non-logged in user` },
                { type: `Test Description`, description: `Verify that signup popup appears when non-logged in user accesses Direct Content Launch URL` }
            );
            await learnerHome.launchDCL(directContentURL)
        
        // Verify signup popup appears
        await directContent.verifySignupPopup();
        
        // Verify "Already have an account" text and Sign In link
       
        
        console.log("Signup popup verification completed successfully");
    });

    test(`DCL015 - Test signup popup form functionality`, async ({ page, context }) => {
        test.info().annotations.push(
            { type: `Author`, description: `AutoGenerated` },
            { type: `TestCase`, description: `DCL015 - Test signup popup form functionality` },
            { type: `Test Description`, description: `Test filling signup form and form validation in the popup` }
        );

        const { DirectContentLaunch } = await import("../../../pages/DirectContentLaunch");
        const directContent = new DirectContentLaunch(page, context);
        
        const testURL = process.env.DIRECT_CONTENT_URL || directContentURL;
        
        if (!testURL) {
            throw new Error("Direct Content URL not available");
        }

        // Navigate to Direct Content URL
        await directContent.navigateToDirectContentURL(testURL);
        
        // Verify and fill signup form
        await directContent.verifySignupPopup();
        
    });

    
});